In [1]:
import sys  
sys.path.insert(0, 'D:\Files\Sergio\Jupyter Notebook\Libs')
from serialrobot import *
from rot_matrix import *
from tf_matrix import *
from par_or import *
from kinematics import *

In [2]:
na = np.array

# Pregunta 1

In [3]:
print("Se halla la matriz simbolica que representa una rotacion con angulos de Euler ZXY")

Se halla la matriz simbolica que representa una rotacion con angulos de Euler ZXY


In [4]:
phi1, phi2, phi3 = sp.symbols("\phi_1 \phi_2 \phi_3")

R1s = srot(phi1,'z')*srot(phi2,'x')*srot(phi3,'y')
R1s

Matrix([
[-sin(\phi_1)*sin(\phi_2)*sin(\phi_3) + cos(\phi_1)*cos(\phi_3), -sin(\phi_1)*cos(\phi_2), sin(\phi_1)*sin(\phi_2)*cos(\phi_3) + sin(\phi_3)*cos(\phi_1)],
[ sin(\phi_1)*cos(\phi_3) + sin(\phi_2)*sin(\phi_3)*cos(\phi_1),  cos(\phi_1)*cos(\phi_2), sin(\phi_1)*sin(\phi_3) - sin(\phi_2)*cos(\phi_1)*cos(\phi_3)],
[                                      -sin(\phi_3)*cos(\phi_2),              sin(\phi_2),                                       cos(\phi_2)*cos(\phi_3)]])

In [5]:
print("a) ")
R1 = na([[0.949, -0.158, -0.273],
        [-0.235, 0.226, -0.946],
        [0.211, 0.961, 0.177]])
print("Matriz de rotacion en t = 10 segundos: ")
printr(R1)
print("")

#Funcion para hallar angulos ZXY a partir de una matriz de rotacion
def zxy_R(R,a_s = '+'):

    if a_s == '+':
        phi2 = np.arctan2(R[2,1],np.sqrt(R[2,0]**2+R[2,2]**2))
    elif a_s == '-':
        phi2 = np.arctan2(R[2,1],-np.sqrt(R[2,0]**2+R[2,2]**2))

    phi1 = np.arctan2(-R[0,1]/cos(phi2),R[1,1]/cos(phi2))
    phi3 = np.arctan2(-R[2,0]/cos(phi2),R[2,2]/cos(phi2))
    
    return phi1, phi2, phi3

p1, p2, p3 = zxy_R(R1)
angszxy = na([[p1, p2, p3]])

p1n, p2n, p3n = zxy_R(R1,'-')
angszxy_n = na([[p1n, p2n, p3n]])

print("Angulos ZXY de la matriz de rotacion (sexagesimales): ")
print("Tomando la raiz positiva en phi2: ")
printr(angszxy,'d')
print("Tomando la raiz negativa en phi2: ")
printr(angszxy_n,'d')
print("")

print("b) ")
R1_20 = na([[-0.906, 0, 0.423],
        [0.423, 0, 0.906],
        [0, 1, 0]])
print("Matriz de rotacion en t = 20 segundos: ")
printr(R1_20)
print("")

p1, p2, p3 = zxy_R(R1_20)
angszxy = na([[p1, p2, p3]])

print("Se presenta una singularidad al ser: ")
print("phi2 = " + str(np.rad2deg(p2))+"°")
print("Reemplazando este valor en la matriz de rotacion se obtiene: ")

a) 
Matriz de rotacion en t = 10 segundos: 
[[ 0.949 -0.158 -0.273]
 [-0.235  0.226 -0.946]
 [ 0.211  0.961  0.177]]

Angulos ZXY de la matriz de rotacion (sexagesimales): 
Tomando la raiz positiva en phi2: 
[[ 34.958  74.008 -50.008]]
Tomando la raiz negativa en phi2: 
[[-145.042  105.992  129.992]]

b) 
Matriz de rotacion en t = 20 segundos: 
[[-0.906  0.     0.423]
 [ 0.423  0.     0.906]
 [ 0.     1.     0.   ]]

Se presenta una singularidad al ser: 
phi2 = 90.0°
Reemplazando este valor en la matriz de rotacion se obtiene: 


In [6]:
sp.simplify(R1s.subs([(phi2,sp.pi/2)]))

Matrix([
[cos(\phi_1 + \phi_3), 0,  sin(\phi_1 + \phi_3)],
[sin(\phi_1 + \phi_3), 0, -cos(\phi_1 + \phi_3)],
[                   0, 1,                     0]])

In [7]:
print("Se observa que se puede obtener la suma de los dos angulos phi1 y phi 3"
)
phi1_3 = np.rad2deg(np.arctan2(R1_20[1,0],R1_20[0,0]))
print("La suma de phi1 y phi3 es: " + str(np.round(phi1_3,3))+"°")
print("Se puede asumir que phi1 vale 80° y phi3 vale 74.973°")


Se observa que se puede obtener la suma de los dos angulos phi1 y phi 3
La suma de phi1 y phi3 es: 154.973°
Se puede asumir que phi1 vale 80° y phi3 vale 74.973°


# Ejercicio 2

In [8]:
#Funcion para obtener coordenadas de los puntos respecto al sistema del Lidar dado r y angulo
def plidar(r,g):
    g = np.deg2rad(g)
    lx = r*cos(g)
    ly = r*sin(g)
    lz = 0
    pl =  na([[lx],[ly],[lz]])
    return pl

#Coordenadas de los puntos respectos al lidar
pl1 = plidar(2.04, 0)
pl2 = plidar(2.6, 20)
pl3 = plidar(3.39, -30)

#Funcion para hallar la Transformacion homogenea del lidar, respecto al robot dado thetai
def TR_L(th_i): 
    TR_L = tf_trc(0.12,-0.1,0.3).dot(tf_rot(-th_i,'y','d'))
    return TR_L

print("a) ")
#Obtencion de las mediciones del Lidar respecto al sistema del robot
pr1 = np_pT(pl1,TR_L(0))
pr2 = np_pT(pl2,TR_L(35))
pr3 = np_pT(pl3,TR_L(50))

print("Las coordenadas tridimensionales de los puntos medidos por el LiDAR p1, p2 y p3 con respecto al sistema de referencia del robot son: ")
print("")
print("pr1 = ")
printr(pr1)
print("")
print("pr2 = ")
printr(pr2)
print("")
print("pr3 = ")
printr(pr3)
print("")

print("b) ")

#Transformacion del sistema del robot respecto al sistema inercial
CI_R = cuaternion(0.94, 0, 0, 0.34) #Se define el cuaternion
RI_R = Rf_C(CI_R) #Se halla la matriz de rotacion dado el cuaternion
[u, th] = u_th_R(RI_R) #Se halla angulo de giro y eje a partir de R
#print(u, th)
TI_R = tf_rot(th,'z').dot(tf_trc(5,-2,0.2)) #Se realiza la transtormacion

#Obtencion de las mediciones del Lidar respecto al sistema inercial
pI1 = np_pT(pr1,TI_R)
pI2 = np_pT(pr2,TI_R)
pI3 = np_pT(pr3,TI_R)

print("Las coordenadas tridimensionales de p1, p2 y p3 con respecto al sistema de referencia inercial son: ")
print("")
print("pI1 = ")
printr(pI1)
print("")
print("pI2 = ")
printr(pI2)
print("")
print("pI3 = ")
printr(pI3)

a) 
Las coordenadas tridimensionales de los puntos medidos por el LiDAR p1, p2 y p3 con respecto al sistema de referencia del robot son: 

pr1 = 
[[ 2.16]
 [-0.1 ]
 [ 0.3 ]]

pr2 = 
[[2.121]
 [0.789]
 [1.701]]

pr3 = 
[[ 2.007]
 [-1.795]
 [ 2.549]]

b) 
Las coordenadas tridimensionales de p1, p2 y p3 con respecto al sistema de referencia inercial son: 

pI1 = 
[[6.847]
 [2.966]
 [0.5  ]]

pI2 = 
[[6.248]
 [3.625]
 [1.901]]

pI3 = 
[[7.813]
 [1.566]
 [2.749]]


# Ejercicio 3

# a)
# Utilizaria:
# - Motores brushless DC debido a sus altas velocidades ya que estas se requieren para poder elevar al dron.
# - SBC para el control de alto nivel
# - Baterias LiPo debido a su alta densidad de energia para alimentar al amplificador de potencia que en este caso seria un Electronic Speed Control
# - ESC para el control de los motores (iria conectado a la bateria, al motor y al SBC)
# - Un frame aerodinamico para el mejor desplazamiento en el aire
# - Un autopilot para el control de bajo nivel de los motores.

# b) Si es el mismo dado que girar un angulo theta alrededor de un eje u es lo mismo que girar en un eje - u en sentido negativo a ese eje.

In [9]:
print("c) ")

print("Matriz de rotacion del resultante respecto al inicial:")
T5 = tf_rot(40,'x','d').dot(tf_rot(30,'z','d')).dot(tf_trc(5,0,0)).dot(tf_trc(0,2,0))
printr(T5)
print("")

#Transformacion del sistema inicial respecto al resultante
T5i = np.linalg.inv(T5)

print("La posicion y orientación del sistema inicial con respecto al sistema resultante es: ")
print("Posicion: ")
printr(T5i[0:3,3:])
print("Rotacion: ")
printr(T5i[0:3,:3])

c) 
Matriz de rotacion del resultante respecto al inicial:
[[ 0.866 -0.5    0.     3.33 ]
 [ 0.383  0.663 -0.643  3.242]
 [ 0.321  0.557  0.766  2.72 ]
 [ 0.     0.     0.     1.   ]]

La posicion y orientación del sistema inicial con respecto al sistema resultante es: 
Posicion: 
[[-5.]
 [-2.]
 [ 0.]]
Rotacion: 
[[ 0.866  0.383  0.321]
 [-0.5    0.663  0.557]
 [ 0.    -0.643  0.766]]


# d) Se debe tener 3 eslabones y 3 articulaciones como minimo para obtener 3 grados de libertad segun la formula de Guebler